version: "3"
services:
  app:
    image: dnd-app
    container_name: dnd-app-www
    platform: ${DOCKER_PLATFORM}
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      CONTAINER_ROLE: app
      PHP_IDE_CONFIG: "serverName=dnd-notetaking-app"
  queue:
    image: dnd-app
    container_name: dnd-app-queue
    platform: ${DOCKER_PLATFORM}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: queue
      PHP_IDE_CONFIG: "serverName=dnd-notetaking-app"
      CONTAINER_QUEUE_TYPE: "work"
  scheduler:
    image: dnd-app
    container_name: dnd-app-scheduler
    platform: ${DOCKER_PLATFORM}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - .:/var/www/html
    environment:
      CONTAINER_ROLE: scheduler
      PHP_IDE_CONFIG: "serverName=dnd-notetaking-app"